# Generated by Django 4.1.7 on 2023-03-27 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_buddy_armpower_buddy_bodypower_buddy_legpowr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='armpower',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='bodypower',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='legpowr',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.CreateModel(
            name='ExHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exType', models.CharField(max_length=255)),
                ('exCount', models.IntegerField(verbose_name=10)),
                ('exData', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
