# Generated by Django 4.1.7 on 2023-03-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_buddy_armpower_alter_buddy_bodypower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buddy',
            old_name='legpowr',
            new_name='legpower',
        ),
    ]
