# Generated by Django 4.1.7 on 2023-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_legpowr_buddy_legpower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='armpower',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='bodypower',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='legpower',
            field=models.IntegerField(),
        ),
    ]
