# Generated by Django 4.1.7 on 2023-03-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_buddy_armpower_alter_buddy_bodypower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='armpower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='bodypower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='legpower',
            field=models.IntegerField(default=0),
        ),
    ]
