# Generated by Django 4.2.5 on 2023-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_buddy_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhistory',
            name='exData',
            field=models.DateField(),
        ),
    ]
