# Generated by Django 5.2.17 on 2026-08-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_exhistory_exdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhistory',
            name='exCount',
            field=models.IntegerField(),
        ),
    ]
